// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhmQnmOzEGXC9a_NnD9biSQOcoARzOcYM',
    appId: '1:865252427280:web:823fd7013b484c8dcf2c95',
    messagingSenderId: '865252427280',
    projectId: 'frontend-project-3a2e7',
    authDomain: 'frontend-project-3a2e7.firebaseapp.com',
    storageBucket: 'frontend-project-3a2e7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcv0HIPZF71_4DHOr03i-4Pi-wtXXxiJY',
    appId: '1:865252427280:android:a37c720cd608579dcf2c95',
    messagingSenderId: '865252427280',
    projectId: 'frontend-project-3a2e7',
    storageBucket: 'frontend-project-3a2e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuNgw7KK0eliKOf6LpFPTRIOkEFLkNCS8',
    appId: '1:865252427280:ios:73891fc7587605b9cf2c95',
    messagingSenderId: '865252427280',
    projectId: 'frontend-project-3a2e7',
    storageBucket: 'frontend-project-3a2e7.appspot.com',
    iosClientId: '865252427280-tma1ullm22m70o9sjoucaqf0s1ojsv62.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
